server:
  port: 8080

spring:
  application:
    name: tehnomer
  datasource:
    url: jdbc:postgresql://localhost:5432/tehnomerDB
    username: tework
    password: ksflkOkas23fl9saflKdl349sLfsk1
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    enabled: true 
  mail:
    host: smtp.gmail.com
    port: 587
    username: daniliesaec@gmail.com
    password: jjrnuggqqirhpnxq
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
        debug: true

jwt:
  secret: secretKey123123123sjfsjfksfjklsjfkaksdjaksjdlaks1232jdkajsdlkajdj

logging:
  level:
    org:
      hibernate:
        SQL:
        type: TRACE
    springframework:
      security: DEBUG
    root: INFO
    com:
      example: DEBUG
  file:
    name: logs/myapp.log
    max-size: 10MB
    max-history: 30
